# Generated by Django 5.0.4 on 2024-05-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_for_living', '0002_alter_eventdate_options_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(choices=[('Volunteer', 'Volunteer'), ('Surfer', 'Surfer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='volunteer_preference',
            field=models.CharField(blank=True, choices=[('In Water', 'In Water'), ('Out of Water', 'Out of Water'), ('Wherever', 'Wherever')], max_length=12, null=True),
        ),
    ]
