# Generated by Django 5.0.4 on 2024-05-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_for_living', '0003_alter_registration_registration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='volunteer_preference',
            field=models.CharField(blank=True, choices=[('In Water', 'In Water'), ('Out of Water', 'Out of Water'), ('On Land', 'On Land'), ('Wherever', 'Wherever')], max_length=12, null=True),
        ),
    ]
