# Generated by Django 4.2.16 on 2024-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_for_living', '0006_registration_wetsuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=19, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('home_address', models.TextField()),
                ('home_city', models.CharField(max_length=100)),
                ('home_state', models.CharField(max_length=2)),
                ('home_zip', models.CharField(max_length=10)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('mailing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('mailing_state', models.CharField(blank=True, max_length=2, null=True)),
                ('mailing_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('diagnosis', models.TextField()),
                ('application_reason', models.CharField(choices=[('Medical Equipment', 'Medical Equipment'), ('Home Modification', 'Home Modification'), ('Vehicle Modification', 'Vehicle Modification'), ('Other', 'Other')], max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_funding_sources', models.TextField(blank=True, null=True)),
                ('other_funding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_letter', models.TextField()),
                ('mainecare_denial_upload', models.FileField(blank=True, null=True, upload_to='mainecare_denial')),
                ('vendor_quote_upload', models.FileField(blank=True, null=True, upload_to='vendor_quote')),
                ('letter_of_recommendation_upload', models.FileField(blank=True, null=True, upload_to='letter_of_recommendation')),
                ('refuse_to_disclose', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('how_heard', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
