# Generated by Django 4.2.16 on 2024-09-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equip_for_living', '0007_grantapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='application_reason',
            field=models.CharField(max_length=255),
        ),
    ]
